from fspeclib import *

Function(
    name='cube.io.rc',
    title=LocalizedString(
        en='io'
    ),
    has_pre_exec_init_call=True,
    parameters=[],
    inputs=[],
    outputs=[
        Output(
            name='rc_channel1',
            title='rc_channel1',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel2',
            title='rc_channel2',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel3',
            title='rc_channel3',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel4',
            title='rc_channel4',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel5',
            title='rc_channel5',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel6',
            title='rc_channel6',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel7',
            title='rc_channel7',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel8',
            title='rc_channel8',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel9',
            title='rc_channel9',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel10',
            title='rc_channel10',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel11',
            title='rc_channel11',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel12',
            title='rc_channel12',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel13',
            title='rc_channel13',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel14',
            title='rc_channel14',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel15',
            title='rc_channel15',
            value_type='core.type.f64'
        ),
        Output(
            name='rc_channel16',
            title='rc_channel16',
            value_type='core.type.f64'
        ),
    ],
    state=[],
    parameter_constraints=[],
)
